/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistematsmbfoa;

import com.adriangarcia.metaheuristics.tsmbfoa.Problem; 
import java.awt.BasicStroke;
import java.awt.Color; 
import java.awt.Shape;
import java.text.DecimalFormat; 
import java.util.ArrayList;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.labels.BoxAndWhiskerToolTipGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.category.BoxAndWhiskerRenderer;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer; 
import org.jfree.data.statistics.DefaultBoxAndWhiskerCategoryDataset;
 
import org.jfree.data.xy.DefaultXYDataset;
import org.jfree.util.ShapeUtilities;


/**
 *
 * @author 
 */
public class GraphicsGUI extends javax.swing.JDialog {

    Problem problem;    
    
    public GraphicsGUI(java.awt.Frame parent, boolean modal, Problem problem) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.problem = problem;
        
        this.showGraphics0();
        
//        if (problem.getExecutions() > 1 & problem.getBestKnownValue() > 0) {
//            this.showGraphics1();
//        } else {
//        }
        
        
        this.showGraphics2();                                                   
        this.showBoxPlot();
                                
        this.pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        graphics5 = new javax.swing.JPanel();
        graphics3 = new javax.swing.JPanel();
        graphics6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Graphics");

        graphics5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout graphics5Layout = new javax.swing.GroupLayout(graphics5);
        graphics5.setLayout(graphics5Layout);
        graphics5Layout.setHorizontalGroup(
            graphics5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        graphics5Layout.setVerticalGroup(
            graphics5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        graphics3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout graphics3Layout = new javax.swing.GroupLayout(graphics3);
        graphics3.setLayout(graphics3Layout);
        graphics3Layout.setHorizontalGroup(
            graphics3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1309, Short.MAX_VALUE)
        );
        graphics3Layout.setVerticalGroup(
            graphics3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        graphics6.setBackground(new java.awt.Color(255, 255, 255));
        graphics6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout graphics6Layout = new javax.swing.GroupLayout(graphics6);
        graphics6.setLayout(graphics6Layout);
        graphics6Layout.setHorizontalGroup(
            graphics6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphics6Layout.setVerticalGroup(
            graphics6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graphics3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(graphics5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(graphics6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphics3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graphics6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(graphics5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    
    
               
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphics3;
    private javax.swing.JPanel graphics5;
    private javax.swing.JPanel graphics6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    DefaultXYDataset dataset;
    JFreeChart chart;
    XYPlot plot;
    XYLineAndShapeRenderer renderer;
    ChartPanel chartPane1;
    
    public void showGraphics0(){                
        dataset = new DefaultXYDataset();        
        dataset.addSeries("Best Values ", this.problem.getConvergenceMedia());       
        
        chart = null;
        chart = ChartFactory.createXYLineChart(
                "Independent median execution convergence"
                //this.problem.getNameProblem()
                  //"JMetaBFOP convergence for G09"
                , "Evaluations"
                , "Obj Function"
                , dataset
                ,  PlotOrientation.VERTICAL, false, true, false);                  
         
        ((NumberAxis) chart.getXYPlot().getRangeAxis()).setNumberFormatOverride(new DecimalFormat("#.###############"));                  
         
        plot = (XYPlot) chart.getPlot();                
        renderer = (XYLineAndShapeRenderer) plot.getRenderer();           
        renderer.setSeriesShapesVisible(0, true);
        renderer.setSeriesPaint(0, Color.BLUE);
        
        Shape cross = ShapeUtilities.createDiamond(1);
        renderer.setSeriesShape(0, cross);
        //renderer.setSeriesShape(0, new Ellipse2D.Double(6/2-3, 6/2-3, 2*3, 2*3));
        
        renderer.setSeriesStroke(0, new BasicStroke(2));
        chart.getXYPlot().setRenderer(renderer);
        plot.setDomainGridlinePaint(Color.GRAY);
        plot.setRangeGridlinePaint(Color.GRAY);
        chartPane1 = new ChartPanel(chart);
        chart.getPlot().setBackgroundPaint( new Color(250, 250, 250) );
        
        graph(graphics3, chartPane1);        
    }
    
    public void showGraphics1(){                
        dataset = new DefaultXYDataset();          
                
        dataset.addSeries("Best values ", this.problem.getConvergenceBestValue());       
        
        chart = null;
        chart = ChartFactory.createXYLineChart(
                "Convergence of the best value found"
                , "Generations"
                , "Obj Function"
                , dataset
                ,  PlotOrientation.VERTICAL, false, true, false);                  
                 
        ((NumberAxis) chart.getXYPlot().getRangeAxis()).setNumberFormatOverride(new DecimalFormat("#.###############"));                  
         
        plot = (XYPlot) chart.getPlot();                
        renderer= (XYLineAndShapeRenderer) plot.getRenderer();         
        renderer.setSeriesShapesVisible(0, true);
        renderer.setSeriesPaint(0, Color.RED);
        renderer.setSeriesStroke(0, new BasicStroke(1));
        chart.getXYPlot().setRenderer(renderer);
        
        chartPane1 = new ChartPanel(chart);
//        chartPane1.setDomainZoomable(false);
//        chartPane1.setRangeZoomable(false); 
        
        //graph(graphics2, chartPane1);                
    }
    
    public void showGraphics2(){                
        dataset = new DefaultXYDataset();
        dataset.addSeries("Best values ", this.problem.getDataGraphicsBestResults());
                 
        chart = null;
        chart = ChartFactory.createXYLineChart(
                "Best values found"
                , "Iteration"
                , "Best value"
                , dataset
                ,  PlotOrientation.VERTICAL, false, true, false);                  
         
        if (this.problem.getStatistic()[0] == this.problem.getStatistic()[4]) {
            chart.getXYPlot().getRangeAxis().setRange(this.problem.getStatistic()[0] - 0.00001, this.problem.getStatistic()[4] + 0.00001);                
        }else{
            chart.getXYPlot().getRangeAxis().setRange(this.problem.getStatistic()[0], this.problem.getStatistic()[4]);
        }                                 
        
        ((NumberAxis) chart.getXYPlot().getRangeAxis()).setNumberFormatOverride(new DecimalFormat("#.###############"));                  
         
        plot = (XYPlot) chart.getPlot();           
        renderer= (XYLineAndShapeRenderer) plot.getRenderer();         
        renderer.setSeriesShapesVisible(0, true);
        renderer.setSeriesPaint(0, Color.MAGENTA);
        renderer.setSeriesStroke(0, new BasicStroke(2));
        chart.getXYPlot().setRenderer(renderer);
        
        chartPane1 = new ChartPanel(chart);
        chart.getPlot().setBackgroundPaint( new Color(250, 250, 250) );

        chartPane1.setDomainZoomable(false);
        chartPane1.setRangeZoomable(false); 
        
        graph(graphics5, chartPane1);               
    }
    
    public void showBoxPlot(){
        
        ArrayList<Double> list = new ArrayList();
        for (int i = 0; i < this.problem.getDataGraphicsBestResults()[0].length; i++) {
            list.add(this.problem.getDataGraphicsBestResults()[1][i]);            
        }                
        
        DefaultBoxAndWhiskerCategoryDataset data = new DefaultBoxAndWhiskerCategoryDataset();        
        data.add(list, "bestValue", "");      
        
        
        CategoryAxis xAxis = new CategoryAxis("Iterations");
        NumberAxis yAxis = new NumberAxis("Values");
        yAxis.setAutoRangeIncludesZero(false);
        BoxAndWhiskerRenderer re = new BoxAndWhiskerRenderer();
                
        
        re.setFillBox(true);
        re.setSeriesToolTipGenerator(1, new BoxAndWhiskerToolTipGenerator());
        re.setMeanVisible(false);
        //re.setSeriesPaint(0, new Color( 255,204,0 ));              
        CategoryPlot plot1 = new CategoryPlot(data, xAxis, yAxis, re); 
        
                        
        chart = null;
        chart = new JFreeChart("Best values box plot", plot1);                                 
        
        chartPane1 = new ChartPanel(chart);
        chart.getPlot().setBackgroundPaint( new Color(250, 250, 250) );
        chart.setBackgroundPaint(Color.white);

        graph(graphics6, chartPane1);
    }
    
    private void graph(JPanel panel, ChartPanel chartPane){
        panel.add(chartPane);
        chartPane.setBounds(0, 0, panel.getWidth(), panel.getHeight());    
    }
    
}
