/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistematsmbfoa;

import com.adriangarcia.metaheuristics.tsmbfoa.Configurator;
import java.awt.Frame;
import java.awt.event.KeyEvent;

/**
 *
 * @author José Adrian García López
 */
public class ParameterCalibration extends javax.swing.JDialog {

    private Configurator configuracion1, configuracionAuxiliar;  
    private MainUI poAuxiliar;
    
    public ParameterCalibration(Frame parent, boolean modal, MainUI po) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);   
        this.configuracion1 = new Configurator();
        this.configuracionAuxiliar = new Configurator();
        this.poAuxiliar = po;               
    }
    
    public ParameterCalibration(Frame parent, boolean modal, MainUI po, Configurator configuracion) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); 
        this.configuracion1 = new Configurator();
        this.configuracionAuxiliar = new Configurator();
        this.poAuxiliar = po;          
        this.mostrarConfiguracionRecomendada(configuracion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtBacterias = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTamanoPaso = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtCiclosQuimiotaxis = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtFactorEscalamiento = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtBacteriasReproducir = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtFrecuenciaReproduccion = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtNumeroEvaluaciones = new javax.swing.JTextField();
        btnTerminar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración de parámetros del TS-MBFOA");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter parameter settings", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 16), new java.awt.Color(255, 102, 0))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel19.setText("Bacteria");

        txtBacterias.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtBacterias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBacteriasKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel20.setText("Stepsize");

        txtTamanoPaso.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtTamanoPaso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamanoPasoKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel21.setText("Chemotoxic cycles");

        txtCiclosQuimiotaxis.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtCiclosQuimiotaxis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCiclosQuimiotaxisKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel22.setText("Scaling factor");

        txtFactorEscalamiento.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtFactorEscalamiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFactorEscalamientoKeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel23.setText("Reproduction frequency");

        txtBacteriasReproducir.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtBacteriasReproducir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBacteriasReproducirKeyTyped(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel24.setText("Bacteria to reproduce");

        txtFrecuenciaReproduccion.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtFrecuenciaReproduccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFrecuenciaReproduccionKeyTyped(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel25.setText("Evaluations");

        txtNumeroEvaluaciones.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtNumeroEvaluaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroEvaluacionesKeyTyped(evt);
            }
        });

        btnTerminar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btnTerminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listo.png"))); // NOI18N
        btnTerminar.setText("Finalize");
        btnTerminar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTerminar.setContentAreaFilled(false);
        btnTerminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTerminar.setFocusPainted(false);
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(125, 125, 125)
                        .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBacterias, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroEvaluaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFrecuenciaReproduccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTamanoPaso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCiclosQuimiotaxis, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFactorEscalamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(27, 27, 27)
                                .addComponent(txtBacteriasReproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtBacterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTamanoPaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtCiclosQuimiotaxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtFactorEscalamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtBacteriasReproducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtFrecuenciaReproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtNumeroEvaluaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 37, Short.MAX_VALUE)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mira.png"))); // NOI18N
        jMenuItem2.setText("Show recommendation");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listo1.png"))); // NOI18N
        jMenuItem3.setText("Finalize");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/niveles.png"))); // NOI18N
        jMenuItem1.setText("Parameter characteristics");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.mostrarConfiguracionRecomendada(this.configuracion1);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
                        
        int sb = Integer.parseInt(this.txtBacterias.getText());
        double stepSize = Double.parseDouble(this.txtTamanoPaso.getText());
        int nc = Integer.parseInt(this.txtCiclosQuimiotaxis.getText());
        double scalingFactor = Double.parseDouble(this.txtFactorEscalamiento.getText());
        int bacteriaReproduce = Integer.parseInt(this.txtBacteriasReproducir.getText());
        int repcycle = Integer.parseInt(this.txtFrecuenciaReproduccion.getText());
        int evaluations = Integer.parseInt(this.txtNumeroEvaluaciones.getText());                                        
        
        this.configuracionAuxiliar.setSb(sb);
        this.configuracionAuxiliar.setStepSize(stepSize);
        this.configuracionAuxiliar.setNc(nc);
        this.configuracionAuxiliar.setScalingFactor(scalingFactor);
        this.configuracionAuxiliar.setBacteriaReproduce(bacteriaReproduce);
        this.configuracionAuxiliar.setRepcycle(repcycle);
        this.configuracionAuxiliar.setEvaluations(evaluations);
        
        this.poAuxiliar.mostrarConfiguracionRecomendada(configuracionAuxiliar);                
        
        this.dispose();
        
        
        
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        btnTerminar.doClick();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void txtBacteriasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBacteriasKeyTyped
        validarEntero(evt, 3, this.txtBacterias.getText());
    }//GEN-LAST:event_txtBacteriasKeyTyped

    private void txtCiclosQuimiotaxisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiclosQuimiotaxisKeyTyped
        validarEntero(evt, 3, this.txtCiclosQuimiotaxis.getText());
    }//GEN-LAST:event_txtCiclosQuimiotaxisKeyTyped

    private void txtBacteriasReproducirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBacteriasReproducirKeyTyped
        validarEntero(evt, 3, this.txtBacteriasReproducir.getText());
    }//GEN-LAST:event_txtBacteriasReproducirKeyTyped

    private void txtFrecuenciaReproduccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrecuenciaReproduccionKeyTyped
        validarEntero(evt, 3, this.txtFrecuenciaReproduccion.getText());
    }//GEN-LAST:event_txtFrecuenciaReproduccionKeyTyped

    private void txtNumeroEvaluacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroEvaluacionesKeyTyped
        validarEntero(evt, 5, this.txtNumeroEvaluaciones.getText());
    }//GEN-LAST:event_txtNumeroEvaluacionesKeyTyped

    private void txtTamanoPasoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamanoPasoKeyTyped
        char caracter = evt.getKeyChar();        
        if((Character.isLetter(caracter) || (caracter != '.' && !Character.isDigit(caracter)))) {
		this.getToolkit().beep(); 
		evt.consume();                 
	}
    }//GEN-LAST:event_txtTamanoPasoKeyTyped

    private void txtFactorEscalamientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFactorEscalamientoKeyTyped
        char caracter = evt.getKeyChar();        
        if((Character.isLetter(caracter) || (caracter != '.' && !Character.isDigit(caracter)))) {
		this.getToolkit().beep(); 
		evt.consume();                 
	}
    }//GEN-LAST:event_txtFactorEscalamientoKeyTyped

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextField txtBacterias;
    private javax.swing.JTextField txtBacteriasReproducir;
    private javax.swing.JTextField txtCiclosQuimiotaxis;
    private javax.swing.JTextField txtFactorEscalamiento;
    private javax.swing.JTextField txtFrecuenciaReproduccion;
    private javax.swing.JTextField txtNumeroEvaluaciones;
    private javax.swing.JTextField txtTamanoPaso;
    // End of variables declaration//GEN-END:variables

    public void mostrarConfiguracionRecomendada(Configurator configuracion){
        this.txtBacterias.setText("" + configuracion.getSb());
        this.txtTamanoPaso.setText("" + configuracion.getStepSize());
        this.txtCiclosQuimiotaxis.setText("" + configuracion.getNc());
        this.txtFactorEscalamiento.setText("" + configuracion.getScalingFactor());
        this.txtBacteriasReproducir.setText("" + configuracion.getBacteriaReproduce());
        this.txtFrecuenciaReproduccion.setText("" + configuracion.getRepcycle());
        this.txtNumeroEvaluaciones.setText("" + configuracion.getEvaluations());
    }
    private void validarEntero(KeyEvent evt, int tamano, String entrada){        
        if(!Character.isDigit(evt.getKeyChar()) || entrada.length() >= tamano) {
		this.getToolkit().beep(); 
		evt.consume(); 
	} 
    }
}
